// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * The one and only fullscreen toggle. All three entry points
 * (menu, ⌃⌘F, sidebar button) funnel through this command.
 */
async toggleFullscreen() : Promise<Result<WindowStateSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_fullscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.2.3 (issue #41): Brutal's window is square — the native corner
 * mask (16px in every other theme) drops to 0 while that theme is
 * active. The frontend calls this whenever the effective theme changes
 * (startup + every Appearance switch); fullscreen is square regardless.
 * The AppKit work hops to the main thread — driving the view hierarchy
 * from a tokio worker aborts (the glass.rs lesson).
 */
async setWindowCornersSquare(square: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_corners_square", { square }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fade-out then hide (red light / Close Window). Interruptible:
 * a newer request cancels the ramp and the terminal action still runs
 * from a deterministic state.
 */
async closeWindowWithFade() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window_with_fade") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * First show / dock reopen — fade in from transparent.
 * 
 * v1.3.0 (#51): this is now the cold-start reveal. The main window is
 * created hidden; the frontend calls this once the saved theme has
 * landed, so the window's first visible frame is already themed (dark
 * users never see the Lavender default first). Shows-and-fades when
 * hidden, and is a NO-OP when already visible — dev reloads and other
 * repeat callers must never re-fade a live window.
 * 
 * v1.3.0 (#56): `label` extends the same reveal to secondary windows
 * (the help center), created hidden on the frontend side and revealed
 * by their own page once ready; omitted, it stays the main window's
 * reveal.
 */
async fadeInWindow(label: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fade_in_window", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Queries the current window snapshot (initial state on frontend mount).
 */
async getWindowState() : Promise<Result<WindowStateSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Marks the app as quitting so in-flight fades cancel and future fade
 * commands hide immediately (⌘Q must not wait for an animation).
 */
async markQuitting() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_quitting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.1.2 T7: the actual process exit behind ⌘Q. The macOS menu item is a
 * custom MenuItem (not the predefined Quit) so React can confirm with a
 * live session first; once confirmed (or with no live session) this
 * marks quitting — no fade — and exits. Session teardown runs
 * in the `ExitRequested` handler.
 */
async quitApp() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("quit_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.3.0 (#56): the focused window's label ("main" when nothing else
 * is focused) — the File > Close Window ⌘W action must act on the
 * FRONT window: with the help center open, ⌘W closes it instead of
 * running the main window's close flow behind it.
 */
async focusedWindowLabel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focused_window_label") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full preflight for a candidate project directory (§8 step 2):
 * orphan cleanup → manifest validation → dependency check → port check.
 * Returns the validated manifest so the frontend can show project info.
 * 
 * v1.2.3 (issue #37): preflight never harms the running session — its
 * children are exempt from the orphan cleanup, and ports held only by
 * them pass (they are released when the session stops). Ports held by
 * any other process still conflict.
 */
async preflightProject(path: string) : Promise<Result<Manifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preflight_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cleans up child processes left behind by an abnormal previous exit.
 * Also runs automatically at app startup and at the start of preflight.
 * Children of the live session are never touched (v1.2.3, issue #37).
 */
async cleanupOrphanedProcesses() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_orphaned_processes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts the score server of a validated project (§8). Progress and
 * health updates are delivered via `pnds:session` events. `osc_target` is
 * required (and validated) only for external mode (§9).
 */
async startProject(path: string, mode: string, lanIp: string, oscTarget: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_project", { path, mode, lanIp, oscTarget }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops the running score server (§11). Idempotent.
 */
async stopProject() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current session snapshot (frontend restores state on load).
 */
async getSessionState() : Promise<Result<SessionSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §7.5: set the master volume (0-100, dB-linear; live via OSC in internal
 * mode). External/none modes store the value but apply nothing.
 */
async setMasterVolume(percent: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_master_volume", { percent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Usable LAN IPv4 addresses (§4). The user must choose when more than
 * one exists; loopback is never offered.
 */
async listLanAddresses() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_lan_addresses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §7.6: CoreAudio output devices with their usable output channel count
 * at the given project sample rate, plus the system default. Always
 * re-enumerates (the settings UI must see hot-plugged devices), while
 * session start reuses the process cache.
 */
async listOutputDevices(sampleRate: number) : Promise<Result<AudioDeviceCapabilities, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_output_devices", { sampleRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Issue #21: the sample rates the Settings Audio section offers — the
 * standard rates supported across all enumerated output devices
 * (deduplicated, ascending). Enumeration failure or an empty union already
 * falls back to the full standard list inside, so the frontend never has
 * to handle an error or an empty list.
 */
async listSupportedSampleRates() : Promise<number[]> {
    return await TAURI_INVOKE("list_supported_sample_rates");
},
/**
 * v1.2.0 (issue #14): occupancy of one TCP port — the listening process's
 * pid, name and full command line, or None when free. The Settings port
 * section queries this on open / manual refresh (no polling).
 */
async checkPortStatus(port: number) : Promise<Result<PortStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_port_status", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.2.0 (issue #14): release an occupied port — SIGTERM → grace → SIGKILL
 * on the freshly-resolved occupant (same escalation as §11 child cleanup).
 * Returns the port's post-release status; the caller refreshes from it.
 */
async releasePort(port: number) : Promise<Result<PortStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("release_port", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pre-flight info for the pack UI: the `<name>-<version>.pnds` path the
 * pack would produce and whether it already exists (overwrite confirm),
 * plus the same manifest/dependency validations the pack itself runs.
 */
async getBundleOutputInfo(path: string) : Promise<Result<BundleOutputInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_bundle_output_info", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Packs the project at `path` (spec issue #16: staging-isolated, no npm,
 * source untouched). `overwrite` must be true to replace an existing
 * output — the UI confirms first via [`get_bundle_output_info`].
 */
async packProjectBundle(path: string, overwrite: boolean) : Promise<Result<PackResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_project_bundle", { path, overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Installs a `.pnds` into `bundles/<id>-<version>/` (always reinstalling
 * over an existing install) and returns the installed project directory —
 * the frontend then runs the normal open flow from there.
 */
async installBundle(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_bundle", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes the extracted bundle directory behind a history entry when (and
 * only when) it is a direct child of the app-managed `bundles/` root.
 * `Ok(false)` = not a managed install, nothing was touched.
 */
async reclaimProjectBundle(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reclaim_project_bundle", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Atomically drains the queue of `.pnds` paths macOS asked the App to open.
 */
async takePendingBundleOpens() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_pending_bundle_opens") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The ⌘O picker: one native panel that accepts a project directory or a
 * `.pnds` bundle file (see `open_panel.rs` for why the dialog plugin can't
 * do this). Synchronous on purpose — the modal panel must block its caller
 * while running on the main thread.
 */
async pickProjectOrBundle(title: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_project_or_bundle", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compiles the project's SynthDef sources and verifies the manifest's
 * artifact references (contract: def name = artifact file name = manifest
 * reference). Fails with the sclang output when compilation fails.
 */
async compileProjectSynthdefs(path: string) : Promise<Result<SynthdefCompileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compile_project_synthdefs", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.2.0 (issue #18): the built-in utility tools behind the Utilities
 * folder. Returns each tool's stable project path (run in place from the
 * app resources) and manifest name, in registry order. With nothing staged
 * (a dev checkout that has not run `npm run utilities:fetch`), the list is
 * empty.
 */
async builtinUtilities() : Promise<Result<BuiltinUtility[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("builtin_utilities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.3.0 (issue #53): the help center's corpus — every shipped document
 * as raw markdown, in manifest order, from the locale's language tree
 * (#68; the frontend passes the resolved UI locale). Reads the files
 * on every call so dev edits show up without a restart; at the
 * corpus's scale this is a few milliseconds.
 */
async helpCorpus(locale: string) : Promise<Result<HelpCorpusDocument[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("help_corpus", { locale }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveals the app data directory in Finder, creating it if needed.
 */
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveals the app log directory in Finder. This is the root the log plugin
 * writes to (macOS: `~/Library/Logs/<bundle-id>`); it is created on demand
 * because a fresh install may not have logged anything yet.
 */
async openAppLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { 
/**
 * Legacy light/dark/system field — load-only since v1.2.3: the App is
 * fixed-light and the UI theme lives in `color_theme` below. Kept (and
 * still validated) so pre-v1.2.3 files round-trip losslessly; reserved
 * for a future "follow the system" mode.
 */
theme: string; 
/**
 * v1.2.3 (issue #38): the app color theme driving the root node's
 * `data-color-theme` attribute. Enum-validated at the save boundary;
 * the legacy `midnight` (renamed to `brutal` in #41's second
 * redirect) and `glass` (abandoned ticket) values stay accepted so
 * stored preferences keep validating — the frontend maps the former
 * to `brutal` and falls back to `lavender` for anything its build
 * cannot render. App-local, never touches project manifests.
 */
colorTheme?: string; 
/**
 * User's preferred language (V1 ships English-only)
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * Chosen CoreAudio output device name. `None` = system default.
 * This is an app-local preference and never touches project manifests.
 */
outputDevice?: string | null; 
/**
 * Issue #20: global audio sample rate (Hz). The App's sole audio
 * authority — scsynth boots and device capabilities resolve at this
 * rate; a manifest's legacy `audio.scsynth.sampleRate` (when still
 * present) is read and ignored. `None` = unset → 48000. App-local,
 * never touches project manifests.
 */
sampleRate?: number | null; 
/**
 * Last valid external OSC target per project id.
 */
oscTargets?: Partial<{ [key in string]: string }>; 
/**
 * Recently-opened project paths. Appended on open, kept across
 * launches. Removing from the sidebar drops it here.
 */
recentProjects?: string[]; 
/**
 * v1.1.2: one-level performance folders (set lists). Membership only —
 * the trusted list above stays the master list, so deleting a folder
 * merely returns its projects to the ungrouped section.
 */
projectFolders?: ProjectFolder[]; 
/**
 * v1.1.2 T6: user-chosen display name per project path (spec issue #10).
 * Absent entry = derived path-basename name. Never touches manifests.
 */
projectDisplayNames?: Partial<{ [key in string]: string }>; 
/**
 * v1.2.0 (issue #16): manifest-declared project name per path, learned
 * on every successful preflight. The project listings show it (a user
 * override above always wins) so a bundle install reads as its manifest
 * name, not its `<id>-<version>` directory. Never touches manifests.
 */
projectManifestNames?: Partial<{ [key in string]: string }>; 
/**
 * v1.3.0 (issue #55): resource paths of the built-in utilities this
 * install has already offered to the Utilities folder. Every shipped
 * tool is offered exactly once — a newly shipped tool (TND joining
 * in v1.3.0) reaches upgrade installs on their next launch, while a
 * user's later removal sticks because the path stays recorded.
 * Absent in pre-v1.3.0 files: a shipped path already present in the
 * index counts as offered, so the record backfills silently.
 */
offeredUtilities?: string[] }
export type AudioConfig = { defaultMode: string; supportedModes: string[]; 
/**
 * Discrete project output signals (manifest.md): 1..=64, default 2.
 * Not a speaker layout — the App never downmixes.
 */
outputChannels?: number; synthdefs: string[] | null; scsynth: ScsynthConfig | null; 
/**
 * Debug-only fallback for standalone runs. The App must never use it;
 * internal mode OSC targets are always dynamically assigned (manifest.md).
 */
standaloneTarget: string | null }
/**
 * §7.6: sample-rate-aware device capabilities (name = scsynth -H value).
 */
export type AudioDeviceCapabilities = { devices: AudioOutputDevice[]; sampleRate: number }
/**
 * §7.6: one CoreAudio output device and what it can do at the project's
 * sample rate. `maxOutputChannels` is 0 when no configuration of the
 * device supports that rate.
 */
export type AudioOutputDevice = { name: string; isDefault: boolean; maxOutputChannels: number }
/**
 * One tool as the frontend sees it: its registry id, the stable project
 * path inside the app resources, and its manifest-declared display name.
 */
export type BuiltinUtility = { 
/**
 * Registry identity of the tool — stable across every staging root
 * (release resources, a dev checkout, a debug target dir), so the
 * frontend can tell "same tool at a new root" from "new tool".
 */
id: string; 
/**
 * Absolute path of the unpacked tool project, run in place.
 */
path: string; 
/**
 * The manifest-declared display name, so a clean install lists the
 * Utilities entries by name before their first preflight.
 */
name: string }
export type BundleOutputInfo = { outputPath: string; exists: boolean }
/**
 * §7.1: the Internal channel plan computed at session start.
 */
export type ChannelPlan = { 
/**
 * N: discrete signals the project produces (manifest audio.outputChannels).
 */
projectChannels: number; 
/**
 * H: channels the output device offers at the project sample rate.
 */
deviceChannels: number; 
/**
 * K: channels actually bridged to hardware, min(N, H).
 */
bridgedChannels: number; 
/**
 * B: first private project bus; equals K.
 */
privateBusStart: number }
export type HealthAudio = { 
/**
 * `starting | ready | error | disabled` (disabled = none mode, §9)
 */
status: string; target?: string | null; error?: string | null }
/**
 * Runtime-contract §5 health payload. Only the contract fields are modeled; the App must
 * not rely on anything else.
 */
export type HealthPayload = { 
/**
 * `starting | ready | error | stopping`
 */
status: string; projectId?: string | null; audioMode?: string | null; audio?: HealthAudio | null; scoreServer?: HealthScoreServer | null }
export type HealthScoreServer = { performerPort?: number | null; monitorPort?: number | null; error?: string | null }
/**
 * One help document exactly as the frontend receives it: its stable id,
 * its language-tree-relative path (the base the help window resolves
 * the corpus's cross-document markdown links against — #56 user
 * report), and the raw markdown. Titles and sections are the
 * frontend's to derive (it owns the markdown structure pass).
 */
export type HelpCorpusDocument = { id: string; path: string; markdown: string }
export type Manifest = { schemaVersion: number; id: string; name: string; version: string; description: string | null; scoreServer: ScoreServer; audio: AudioConfig }
export type PackResult = { outputPath: string; sha256: string }
/**
 * Who is listening on a project port.
 */
export type PortOccupant = { pid: number; 
/**
 * Short process name — the first token of the full command line.
 */
name: string; 
/**
 * Full command line, for the confirm dialog and the error page.
 */
commandLine: string }
/**
 * Occupancy of one TCP port.
 */
export type PortStatus = { port: number; occupant: PortOccupant | null }
/**
 * A named one-level group of project paths (spec issue #4).
 */
export type ProjectFolder = { id: string; name: string; projectPaths: string[] }
export type ScoreServer = { entry: string; workingDirectory: string; performerPort: number; monitorPort: number }
export type ScsynthConfig = { 
/**
 * Issue #20: legacy field, read and ignored. The App's global
 * sample-rate preference is the sole boot authority; manifests no
 * longer declare `sampleRate` and validation never requires it. Kept
 * on the struct (with a placeholder default) so manifests that still
 * carry it — existing works, bundled .pnds — load losslessly.
 */
sampleRate?: number; blockSize: number; audioBusChannels: number }
/**
 * Session snapshot emitted to the frontend as the `pnds:session` event.
 */
export type SessionSnapshot = { 
/**
 * `idle | starting | ready | error | stopping`
 */
status: string; projectName: string | null; projectPath: string | null; audioMode: string | null; lanIp: string | null; oscTarget: string | null; health: HealthPayload | null; error: string | null; outputTail: string[]; 
/**
 * Master volume percent (§7.5; new N<=2 sessions always start at 80,
 * N>2 sessions are fixed at 100).
 */
volume: number; 
/**
 * Five-stage loading animation dot (1–5); app-behavior「Loading」.
 */
startupStage: number; 
/**
 * §7.1: internal channel plan (N/H/K/B), present for internal sessions.
 */
channelPlan: ChannelPlan | null; 
/**
 * Final CoreAudio output device in use (internal sessions).
 */
outputDevice: string | null }
export type SynthdefCompileResult = { 
/**
 * The sclang binary this run used (standard app path or PATH hit).
 */
sclangPath: string; 
/**
 * Basenames of the `.scsyndef` artifacts written during this run
 * (modified within the run window), sorted.
 */
produced: string[]; 
/**
 * The `manifest.audio.synthdefs` references confirmed on disk after
 * the compile (empty for projects that do not support internal mode).
 */
verified: string[] }
/**
 * Window state broadcast to the frontend (`pnds:window` event).
 */
export type WindowStateSnapshot = { 
/**
 * Native macOS fullscreen state.
 */
fullscreen: boolean; 
/**
 * Whether the sidebar's custom traffic lights should be visible.
 * False while the native (unified) title bar is showing.
 */
showCustomTrafficLights: boolean; 
/**
 * Monotonic counter — bumped on every fullscreen/fade transition so
 * the frontend can re-sync. Independent of the monitor reload nonce:
 * fullscreen changes never reload the monitor.
 */
generation: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
