// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * The one and only fullscreen toggle. All three entry points
 * (menu, ⌃⌘F, sidebar button) funnel through this command.
 */
async toggleFullscreen() : Promise<Result<WindowStateSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_fullscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.2.3 (issue #41): Brutal's window is square — the native corner
 * mask (16px in every other theme) drops to 0 while that theme is
 * active. The frontend calls this whenever the effective theme changes
 * (startup + every Appearance switch); fullscreen is square regardless.
 * The AppKit work hops to the main thread — driving the view hierarchy
 * from a tokio worker aborts (the glass.rs lesson).
 */
async setWindowCornersSquare(square: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_corners_square", { square }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fade-out then hide (red light / Close Window). Interruptible:
 * a newer request cancels the ramp and the terminal action still runs
 * from a deterministic state.
 */
async closeWindowWithFade() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window_with_fade") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * First show / dock reopen — fade in from transparent.
 * 
 * v1.3.0 (#51): this is now the cold-start reveal. The main window is
 * created hidden; the frontend calls this once the saved theme has
 * landed, so the window's first visible frame is already themed (dark
 * users never see the Lavender default first). Shows-and-fades when
 * hidden, and is a NO-OP when already visible — dev reloads and other
 * repeat callers must never re-fade a live window.
 * 
 * v1.3.0 (#56): `label` extends the same reveal to secondary windows
 * (the help center), created hidden on the frontend side and revealed
 * by their own page once ready; omitted, it stays the main window's
 * reveal.
 * 
 * #135 follow-up (venue-screen report): for the projection window the
 * reveal also ACTIVATES the webview — see the webview-level focus
 * below.
 */
async fadeInWindow(label: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fade_in_window", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Queries the current window snapshot (initial state on frontend mount).
 */
async getWindowState() : Promise<Result<WindowStateSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Marks the app as quitting so in-flight fades cancel and future fade
 * commands hide immediately (⌘Q must not wait for an animation).
 */
async markQuitting() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_quitting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.1.2 T7: the actual process exit behind ⌘Q. The macOS menu item is a
 * custom MenuItem (not the predefined Quit) so React can confirm with a
 * live session first; once confirmed (or with no live session) this
 * marks quitting — no fade — and exits. Session teardown runs
 * in the `ExitRequested` handler.
 */
async quitApp() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("quit_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.3.0 (#56): the focused window's label ("main" when nothing else
 * is focused) — the File > Close Window ⌘W action must act on the
 * FRONT window: with the help center open, ⌘W closes it instead of
 * running the main window's close flow behind it.
 */
async focusedWindowLabel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focused_window_label") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads the stored material and re-derives its standing against the
 * CURRENT saved domain preference and clock. `Ok(None)` = nothing
 * imported yet.
 */
async loadHttpsCertificate() : Promise<Result<HttpsValidationOutcome | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_https_certificate") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validates the two picked files (full chain + matching key) against
 * the given domain and, only on success, atomically replaces the
 * stored material. Failure leaves the previous material untouched.
 */
async importHttpsCertificate(domain: string, certificatePemPath: string, privateKeyPemPath: string) : Promise<Result<HttpsValidationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_https_certificate", { domain, certificatePemPath, privateKeyPemPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the stored material (the settings「清除」button). Plain
 * config fields survive in preferences — this only clears the
 * certificate/key file.
 */
async clearHttpsCertificate() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_https_certificate") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full service status: registration, control-plane liveness, listeners,
 * upstreams, mapping and counters. Never fails — a down daemon is a
 * status fact (see `dns::daemon_status`).
 */
async dnsServiceStatus() : Promise<DnsServiceStatus> {
    return await TAURI_INVOKE("dns_service_status");
},
/**
 * Enables the background DNS service. `upstreams` is the operator's
 * forwarding list (IP[:port] entries); blank entries fall back to the
 * defaults. Blocks until the approval flow and readiness poll finish.
 */
async dnsServiceEnable(upstreams: string[] | null, listenIp: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dns_service_enable", { upstreams, listenIp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pushes the operator's current config to a RUNNING daemon (settings
 * commits and App launch call this; a down daemon simply reports so —
 * the config applies on the next enable).
 */
async dnsServiceApplyConfig(upstreams: string[] | null, listenIp: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dns_service_apply_config", { upstreams, listenIp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disables the background DNS service (unregisters the LaunchDaemon —
 * the daemon stops, the port is freed, the authorization is removed).
 */
async dnsServiceDisable() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dns_service_disable") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens System Settings → Login Items — the recovery path when the
 * daemon registration awaits approval (the operator dismissed the
 * approval dialog; the status row routes here).
 */
async dnsServiceOpenSystemSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dns_service_open_system_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full preflight for a candidate project directory (§8 step 2):
 * orphan cleanup → manifest validation → dependency check → port check.
 * Returns the validated manifest so the frontend can show project info.
 * 
 * v1.2.3 (issue #37): preflight never harms the running session — its
 * children are exempt from the orphan cleanup, and ports held only by
 * them pass (they are released when the session stops). Ports held by
 * any other process still conflict.
 */
async preflightProject(path: string) : Promise<Result<Manifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preflight_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.5.0 (#125): reads a project's root README.md for the main area's
 * display routing — the read policy (missing pieces, size cap, readable
 * errors) lives in `project::readme`. `locale` (user report after #127)
 * is the App's resolved UI language: a `README.<locale>.md` variant is
 * preferred when the project ships one, else the plain `README.md`.
 */
async readProjectReadme(path: string, locale: string | null) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_project_readme", { path, locale }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.5.0 (README cover page): reads the project's optional cover image
 * (`cover.png` → `cover.jpg` → `cover.jpeg` → `cover.webp`) as a base64
 * data URL for the README panel's band. The read policy (probe order,
 * missing pieces, size cap, readable errors) lives in `project::cover`.
 */
async readProjectCover(path: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_project_cover", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cleans up child processes left behind by an abnormal previous exit.
 * Also runs automatically at app startup and at the start of preflight.
 * Children of the live session are never touched (v1.2.3, issue #37).
 */
async cleanupOrphanedProcesses() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_orphaned_processes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts the score server of a validated project (§8). Progress and
 * health updates are delivered via `pnds:session` events. `osc_target` is
 * required (and validated) only for external mode (§9).
 * 
 * v1.3.2 (issue #77): the command boundary constructs the `StartRequest`
 * record once — everything below this layer reads from the record, and
 * future start inputs (v1.4.0's hub variables) widen fields, not the
 * four-layer positional chain.
 */
async startProject(path: string, mode: AudioMode, lanIp: string, oscTarget: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_project", { path, mode, lanIp, oscTarget }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops the running score server (§12). Idempotent.
 */
async stopProject() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current session snapshot (frontend restores state on load).
 */
async getSessionState() : Promise<Result<SessionSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.5.0 (#130): toggles the projection start gate (投影开演 ⇄ 撤回).
 * Rust-authoritative and session-level: the ▶ button in the monitor
 * title bar, the ⌘⏎ menu accelerator and the projection window all
 * read the gate from the session snapshots this publishes — an
 * occluded webview cannot hold a stale view of it.
 */
async toggleProjectionStart() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_projection_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §7.5: set the master volume (0-100, dB-linear; live via OSC in internal
 * mode). External/none modes store the value but apply nothing.
 */
async setMasterVolume(percent: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_master_volume", { percent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Usable LAN IPv4 addresses (§4). The user must choose when more than
 * one exists; loopback is never offered.
 */
async listLanAddresses() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_lan_addresses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §7.6: CoreAudio output devices with their usable output channel count
 * at the given project sample rate, plus the system default. Always
 * re-enumerates (the settings UI must see hot-plugged devices), while
 * session start reuses the process cache.
 */
async listOutputDevices(sampleRate: number) : Promise<Result<AudioDeviceCapabilities, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_output_devices", { sampleRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Issue #21: the sample rates the Settings Audio section offers — the
 * standard rates supported across all enumerated output devices
 * (deduplicated, ascending). Enumeration failure or an empty union already
 * falls back to the full standard list inside, so the frontend never has
 * to handle an error or an empty list.
 */
async listSupportedSampleRates() : Promise<number[]> {
    return await TAURI_INVOKE("list_supported_sample_rates");
},
/**
 * v1.2.0 (issue #14): occupancy of one TCP port — the listening process's
 * pid, name and full command line, or None when free. The Settings port
 * section queries this on open / manual refresh (no polling).
 */
async checkPortStatus(port: number) : Promise<Result<PortStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_port_status", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.2.0 (issue #14): release an occupied port — SIGTERM → grace → SIGKILL
 * on the freshly-resolved occupant (same escalation as §12 child cleanup).
 * Returns the port's post-release status; the caller refreshes from it.
 */
async releasePort(port: number) : Promise<Result<PortStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("release_port", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pre-flight info for the pack UI: the `<name>-<version>.pnds` path the
 * pack would produce and whether it already exists (overwrite confirm),
 * plus the same manifest/dependency validations the pack itself runs.
 */
async getBundleOutputInfo(path: string) : Promise<Result<BundleOutputInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_bundle_output_info", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Packs the project at `path` (spec issue #16: staging-isolated, no npm,
 * source untouched). `overwrite` must be true to replace an existing
 * output — the UI confirms first via [`get_bundle_output_info`].
 */
async packProjectBundle(path: string, overwrite: boolean) : Promise<Result<PackResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_project_bundle", { path, overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Installs a `.pnds` into `bundles/<id>-<version>/` (always reinstalling
 * over an existing install) and returns the installed project directory —
 * the frontend then runs the normal open flow from there.
 */
async installBundle(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_bundle", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes the extracted bundle directory behind a history entry when (and
 * only when) it is a direct child of the app-managed `bundles/` root.
 * `Ok(false)` = not a managed install, nothing was touched.
 */
async reclaimProjectBundle(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reclaim_project_bundle", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.4.0 (#59): the setlist export pre-flight — per project the same
 * packability gate a pack would run plus the manifest identity and the
 * derived `.pnds` file name, so the frontend can assemble set.json
 * before anything is written.
 */
async getSetlistExportInfo(paths: string[]) : Promise<Result<SetlistProjectInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setlist_export_info", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.4.0 (#59): packs every project (in list order) into `destDir`, then
 * writes the frontend-serialized set.json and the folder's
 * self-description README.md beside them (#126 — frontend-composed from
 * the folder's name + intro; the retired README.txt instructions file
 * is removed best-effort). A failure removes everything this run wrote
 * — a partial export never reads as complete. Each pack is announced on
 * `pnds:setlist-export-progress` (`{ done, total, fileName }`, done
 * 0-based) so the UI can show per-project progress.
 */
async exportSetlist(destDir: string, setlistJson: string, readme: string, projectPaths: string[]) : Promise<Result<SetlistExportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_setlist", { destDir, setlistJson, readme, projectPaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.4.0 (#63): reads a setlist export directory for the import — the
 * raw set.json body (the frontend's `parseSetlist` validates it) plus
 * every `.pnds` beside it with its probed identity. Directories without
 * a set.json error out; the frontend routing seam reads exactly that as
 * "not a setlist export" and falls through to the normal open flow.
 */
async readSetlist(dir: string) : Promise<Result<SetlistReadout, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_setlist", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Atomically drains the queue of `.pnds` paths macOS asked the App to open.
 */
async takePendingBundleOpens() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_pending_bundle_opens") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The ⌘O picker: one native panel that accepts a project directory or a
 * `.pnds` bundle file (see `open_panel.rs` for why the dialog plugin can't
 * do this). Synchronous on purpose — the modal panel must block its caller
 * while running on the main thread.
 */
async pickProjectOrBundle(title: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_project_or_bundle", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compiles the project's SynthDef sources and verifies the manifest's
 * artifact references (contract: def name = artifact file name = manifest
 * reference). Fails with the sclang output when compilation fails.
 */
async compileProjectSynthdefs(path: string) : Promise<Result<SynthdefCompileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compile_project_synthdefs", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.2.0 (issue #18): the built-in utility tools behind the Utilities
 * folder. Returns each tool's stable project path (run in place from the
 * app resources) and manifest name, in registry order. With nothing staged
 * (a dev checkout that has not run `npm run utilities:fetch`), the list is
 * empty.
 */
async builtinUtilities() : Promise<Result<BuiltinUtility[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("builtin_utilities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.3.0 (issue #53): the help center's corpus — every shipped document
 * as raw markdown, in manifest order, from the locale's language tree
 * (#68; the frontend passes the resolved UI locale). Reads the files
 * on every call so dev edits show up without a restart; at the
 * corpus's scale this is a few milliseconds.
 */
async helpCorpus(locale: string) : Promise<Result<HelpCorpusDocument[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("help_corpus", { locale }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveals the app data directory in Finder, creating it if needed.
 */
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveals the app log directory in Finder. This is the root the log plugin
 * writes to (macOS: `~/Library/Logs/<bundle-id>`); it is created on demand
 * because a fresh install may not have logged anything yet.
 */
async openAppLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1.4.2 (#110): the installed Safari version — the user-facing proxy for
 * the system WebKit. WKWebView's `navigator.userAgent` is frozen at
 * `AppleWebKit/605.1.15` (since Safari 13), so the frontend cannot learn
 * the engine version from JS; Safari ships every system WebKit update, so
 * its bundle version ("15.1" / "16.4" / "17.6" …) is the number the
 * baseline contract speaks in. `None` when the bundle is missing or
 * carries no readable version — the frontend treats unknown as "stay
 * silent", keeping the zero-disturbance half of the contract.
 */
async systemSafariVersion() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("system_safari_version") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
helpReadyEvent: HelpReadyEvent,
openBundleEvent: OpenBundleEvent,
projectionWindowEvent: ProjectionWindowEvent,
sessionSnapshotEvent: SessionSnapshotEvent,
setlistExportProgressEvent: SetlistExportProgressEvent,
windowFocusEvent: WindowFocusEvent,
windowStateEvent: WindowStateEvent
}>({
helpReadyEvent: "help-ready-event",
openBundleEvent: "open-bundle-event",
projectionWindowEvent: "projection-window-event",
sessionSnapshotEvent: "session-snapshot-event",
setlistExportProgressEvent: "setlist-export-progress-event",
windowFocusEvent: "window-focus-event",
windowStateEvent: "window-state-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { 
/**
 * Legacy light/dark/system field — load-only since v1.2.3: the App is
 * fixed-light and the UI theme lives in `color_theme` below. Kept (and
 * still validated) so pre-v1.2.3 files round-trip losslessly; reserved
 * for a future "follow the system" mode.
 */
theme: string; 
/**
 * v1.2.3 (issue #38): the app color theme driving the root node's
 * `data-color-theme` attribute. Enum-validated at the save boundary;
 * the legacy `midnight` (renamed to `brutal` in #41's second
 * redirect) and `glass` (abandoned ticket) values stay accepted so
 * stored preferences keep validating — the frontend maps renamed
 * values to their successors and falls back to `pond` for anything
 * its build cannot render. App-local, never touches project manifests.
 */
colorTheme?: string; 
/**
 * User's preferred language (V1 ships English-only)
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * Chosen CoreAudio output device name. `None` = system default.
 * This is an app-local preference and never touches project manifests.
 */
outputDevice?: string | null; 
/**
 * Issue #20: global audio sample rate (Hz). The App's sole audio
 * authority — scsynth boots and device capabilities resolve at this
 * rate; a manifest's legacy `audio.scsynth.sampleRate` (when still
 * present) is read and ignored. `None` = unset → 48000. App-local,
 * never touches project manifests.
 */
sampleRate?: number | null; 
/**
 * Last valid external OSC target per project id.
 */
oscTargets?: Partial<{ [key in string]: string }>; 
/**
 * Recently-opened project paths. Appended on open, kept across
 * launches. Removing from the sidebar drops it here.
 */
recentProjects?: string[]; 
/**
 * v1.1.2: one-level performance folders (set lists). Membership only —
 * the trusted list above stays the master list, so deleting a folder
 * merely returns its projects to the ungrouped section.
 */
projectFolders?: ProjectFolder[]; 
/**
 * v1.1.2 T6: user-chosen display name per project path (spec issue #10).
 * Absent entry = derived path-basename name. Never touches manifests.
 */
projectDisplayNames?: Partial<{ [key in string]: string }>; 
/**
 * v1.2.0 (issue #16): manifest-declared project name per path, learned
 * on every successful preflight. The project listings show it (a user
 * override above always wins) so a bundle install reads as its manifest
 * name, not its `<id>-<version>` directory. Never touches manifests.
 */
projectManifestNames?: Partial<{ [key in string]: string }>; 
/**
 * v1.3.0 (issue #55): resource paths of the built-in utilities this
 * install has already offered to the Utilities folder. Every shipped
 * tool is offered exactly once — a newly shipped tool (TND joining
 * in v1.3.0) reaches upgrade installs on their next launch, while a
 * user's later removal sticks because the path stays recorded.
 * Absent in pre-v1.3.0 files: a shipped path already present in the
 * index counts as offered, so the record backfills silently.
 */
offeredUtilities?: string[]; 
/**
 * v1.4.0 (issue #58): this machine's node identity for telematic
 * performance — global, set once in the Settings「节点」section, never
 * per-project. `None`/blank = never set (the「设置节点」gate blocks
 * telematic starts until all three node fields are filled).
 * Whitespace-only counts as unset at the injection seam.
 */
nodeName?: string | null; 
/**
 * v1.4.0 (issue #58): the telematic hub's full URL (`wss://host[:port]`).
 * The token NEVER rides this string — it has its own field below and
 * only ever travels in the injected `PNDS_HUB_TOKEN` variable.
 */
hubUrl?: string | null; 
/**
 * v1.4.0 (issue #58): the hub access token, stored as its own field,
 * displayed masked in the UI and never logged, never concatenated
 * into URLs. Injection is the only consumer.
 */
hubToken?: string | null; 
/**
 * v1.4.0 (issue #58): telematic room group number (1..=3) per project
 * manifest id — the user-visible「Room」dropdown. The App derives
 * the wire room as `{manifest.id}_{group}`; absent entry = group 1.
 * Persisted per project and never reset: crash recovery must land a
 * machine back in its own group's room (ADR-0004).
 */
hubRooms?: Partial<{ [key in string]: number }>; 
/**
 * v1.5.0 (user request after #131): the PROJECTION window's zoom
 * percent (50–200, §v1.1.1 browser-zoom bounds) — remembered across
 * window reopens and app launches, applying to the projection's
 * monitor AND its 简介 screen (the main window's own zoom stays
 * session-local and never rides here). The projection page owns the
 * live value; the MAIN window is the sole preferences writer, so
 * the value reaches storage by event → the serialized queue — two
 * webviews whole-file-writing preferences would race each other.
 * `None` = never set → 100.
 */
projectionZoom?: number | null; 
/**
 * #139: the trusted-HTTPS entry's DNS domain (normalized lowercase,
 * validated at the save boundary by `validate_https_domain_field`).
 * App-local normal config — it rides the preference round-trip like
 * every other settings field; the certificate MATERIAL never does
 * (backend-protected storage, see `https.rs`). `None`/blank = not
 * configured; the entry takes effect only from the next project
 * start (the gateway itself arrives with #140).
 */
httpsDomain?: string | null; 
/**
 * #139: the entry's non-privileged listen port (1024..=65535,
 * validated at the save boundary by `validate_https_port_field`).
 * `None` = not configured.
 */
httpsPort?: number | null; 
/**
 * #140: the operator's entry switch — `Some(true)` activates the
 * trusted-HTTPS gateway for starts of projects that declare
 * `scoreServer.supportsPerformerUrl`. Plain intent: domain, port
 * and material are validated at START (and in the settings
 * section), so switching on with incomplete config surfaces there,
 * never as a mid-start surprise. `None`/`Some(false)` = off, the
 * legacy HTTP flow. Like every entry setting: next start, never a
 * running session.
 */
httpsEnabled?: boolean | null; 
/**
 * #174: the operator's DNS-service switch — `Some(true)` means the
 * background LAN-DNS LaunchDaemon is registered (ordinary
 * forwarding + performance mappings). Plain intent, like
 * `https_enabled`: the service call itself may still fail and the
 * status section reports the real registration state.
 */
dnsEnabled?: boolean | null }
export type AudioConfig = { 
/**
 * The raw-JSON validation below has already rejected unknown mode
 * strings with the contract's error wording before serde ever sees
 * the value; the typed field keeps the rest of the App from
 * re-comparing strings (AudioMode in types.rs).
 */
defaultMode: AudioMode; supportedModes: AudioMode[]; 
/**
 * Discrete project output signals (manifest.md): 1..=64, default 2.
 * Not a speaker layout — the App never downmixes.
 */
outputChannels?: number; synthdefs: string[] | null; scsynth: ScsynthConfig | null; 
/**
 * Debug-only fallback for standalone runs. The App must never use it;
 * internal mode OSC targets are always dynamically assigned (manifest.md).
 */
standaloneTarget: string | null }
/**
 * §7.6: sample-rate-aware device capabilities (name = scsynth -H value).
 */
export type AudioDeviceCapabilities = { devices: AudioOutputDevice[]; sampleRate: number }
/**
 * The audio mode domain (§6.1) shared by the manifest fields, the start
 * request and the session snapshot. The manifest's raw-JSON validation
 * (manifest.rs) still owns the creator-facing error strings; serde pins
 * the wire format (`internal | external | none`).
 */
export type AudioMode = "internal" | "external" | "none"
/**
 * §7.6: one CoreAudio output device and what it can do at the project's
 * sample rate. `maxOutputChannels` is 0 when no configuration of the
 * device supports that rate.
 */
export type AudioOutputDevice = { name: string; isDefault: boolean; maxOutputChannels: number }
/**
 * One tool as the frontend sees it: its registry id, the stable project
 * path inside the app resources, and its manifest-declared display name.
 */
export type BuiltinUtility = { 
/**
 * Registry identity of the tool — stable across every staging root
 * (release resources, a dev checkout, a debug target dir), so the
 * frontend can tell "same tool at a new root" from "new tool".
 */
id: string; 
/**
 * Absolute path of the unpacked tool project, run in place.
 */
path: string; 
/**
 * The manifest-declared display name, so a clean install lists the
 * Utilities entries by name before their first preflight.
 */
name: string }
export type BundleOutputInfo = { outputPath: string; exists: boolean }
/**
 * §7.1: the Internal channel plan computed at session start.
 */
export type ChannelPlan = { 
/**
 * N: discrete signals the project produces (manifest audio.outputChannels).
 */
projectChannels: number; 
/**
 * H: channels the output device offers at the project sample rate.
 */
deviceChannels: number; 
/**
 * K: channels actually bridged to hardware, min(N, H).
 */
bridgedChannels: number; 
/**
 * B: first private project bus; equals K.
 */
privateBusStart: number }
/**
 * Control-plane listener liveness as reported by the daemon.
 */
export type DnsListeners = { udp: boolean; tcp: boolean }
/**
 * The performance mapping facts the daemon currently holds.
 */
export type DnsMappingFacts = { domain: string; ip: string; runId: string; 
/**
 * u32, not u64: specta's TS export forbids BigInt, and neither the
 * session generation nor a lease outlives 2^32.
 */
generation: number; leaseSecondsRemaining: number }
/**
 * #174: the mapping facts a snapshot carries (existing session
 * snapshot — no new channel).
 */
export type DnsMappingState = { status: DnsMappingStatus; domain: string | null; ip: string | null; error: string | null }
/**
 * #174: the DNS mapping's three states. There is no `preparing`: the
 * install + in-daemon verify complete synchronously on the local
 * control socket (milliseconds), so a mapping is either live (`ready`,
 * verified) or it failed (`error`, the session itself unaffected).
 */
export type DnsMappingStatus = 
/**
 * No mapping this session (switch off, entry off, daemon absent).
 */
"off" | 
/**
 * The daemon holds the mapping and its own verify resolved the
 * domain to the session's LAN address.
 */
"ready" | 
/**
 * Install or verify failed — `error` says which. The performance
 * keeps running; phones fall back to manual DNS or the router.
 */
"error"
/**
 * Registration facts from SMAppService (macOS 13+).
 */
export type DnsRegistrationStatus = 
/**
 * Not registered — the daemon is neither enabled nor pending.
 */
"notRegistered" | 
/**
 * Registered and approved — the daemon runs (and returns on boot).
 */
"enabled" | 
/**
 * Registered but awaiting the system's approval (the approval
 * dialog was dismissed; System Settings → Login Items is the fix).
 */
"requiresApproval" | 
/**
 * Registered but the bundle has moved or been removed since.
 */
"notFound"
/**
 * The full status surface the settings section renders.
 */
export type DnsServiceStatus = { registration: DnsRegistrationStatus; 
/**
 * The control plane answered — the daemon process is up and serving.
 */
daemon: boolean; 
/**
 * The bundle ships the LaunchDaemon plist (false in dev builds —
 * enabling requires the installed, bundled App).
 */
plistPresent: boolean; listeners: DnsListeners | null; bindError: string | null; upstreams: string[]; mapping: DnsMappingFacts | null; knownDomains: string[]; stats: JsonValue | null }
export type HealthAudio = { 
/**
 * `starting | ready | error | disabled` (disabled = none mode, §9)
 */
status: string; target?: string | null; error?: string | null }
/**
 * Runtime-contract §5 health payload. Only the contract fields are modeled; the App must
 * not rely on anything else.
 */
export type HealthPayload = { 
/**
 * `starting | ready | error | stopping`
 */
status: string; projectId?: string | null; audioMode?: string | null; audio?: HealthAudio | null; scoreServer?: HealthScoreServer | null }
export type HealthScoreServer = { performerPort?: number | null; monitorPort?: number | null; error?: string | null }
/**
 * One help document exactly as the frontend receives it: its stable id,
 * its language-tree-relative path (the base the help window resolves
 * the corpus's cross-document markdown links against — #56 user
 * report), and the raw markdown. Titles and sections are the
 * frontend's to derive (it owns the markdown structure pass).
 */
export type HelpCorpusDocument = { id: string; path: string; markdown: string }
/**
 * The help window finished booting and is listening for navigation
 * (formerly `pnds:help-ready`). Emitted by the help webview itself;
 * registered here so both windows share one generated name.
 */
export type HelpReadyEvent = Record<string, never>
/**
 * The certificate's standing at the moment of the check. Reload maps
 * revalidation failures into the matching variants; import only ever
 * produces `Valid` / `ExpiringSoon` (anything else was refused).
 */
export type HttpsCertificateStatus = 
/**
 * Valid now, beyond the reminder window.
 */
"valid" | 
/**
 * Valid now but expiring within [`EXPIRY_REMINDER_DAYS`] — renew
 * before the next performance.
 */
"expiringSoon" | "expired" | "notYetValid" | 
/**
 * The stored leaf no longer covers the currently configured domain
 * (the operator changed the domain after import).
 */
"wrongDomain" | 
/**
 * The chain no longer validates against the public root set (e.g. a
 * root was withdrawn), or was never publicly trusted.
 */
"distrusted"
/**
 * What the UI may show about the material. Public certificate facts
 * only — the private key never appears here.
 */
export type HttpsCertificateSummary = { 
/**
 * Subject common name (full DN when no CN is present).
 */
subject: string; issuer: string; 
/**
 * DNS entries of the leaf's Subject Alternative Names.
 */
sans: string[]; 
/**
 * RFC 3339 UTC.
 */
notBefore: string; notAfter: string; 
/**
 * Whole days from `now` until `not_after` (negative once expired).
 * i32 — days, and tauri-specta forbids i64 on the wire.
 */
daysRemaining: number; 
/**
 * `AA:BB:…` uppercase colon-hex SHA-256 of the leaf DER — the
 * operator-visible identity of the stored material.
 */
fingerprint: string; status: HttpsCertificateStatus }
/**
 * #140: the entry facts a snapshot carries (existing session snapshot
 * / typed event — no new channel).
 */
export type HttpsEntryState = { status: HttpsEntryStatus; 
/**
 * The complete performer root URL fixed for this performance
 * (`https://domain:port/`) — present from `preparing` on, so the
 * QR (project-rendered), the menu copy items and this field all
 * read one value.
 */
url: string | null; error: string | null }
/**
 * #140: the entry's four states (spec: at least 关闭/准备/就绪/错误).
 */
export type HttpsEntryStatus = 
/**
 * No entry this session — the legacy HTTP flow is in effect.
 */
"off" | 
/**
 * Launched and probing; the URL is already fixed and injected.
 */
"preparing" | 
/**
 * The local TLS/HTTP probe succeeded — the URL is served end to
 * end. This proves the Host-side tunnel only; it never claims
 * phones' DNS/trust (final device acceptance owns that, §15).
 */
"ready" | 
/**
 * Launch or runtime entry failure — `error` says which step.
 */
"error"
export type HttpsProblem = { code: HttpsProblemCode; detail: string }
/**
 * Why imported material (or stored material at reload) is not usable.
 * `code` keys the localized UI message; `detail` is the English
 * specifics (dates, SANs, paths) shown alongside it.
 */
export type HttpsProblemCode = 
/**
 * A file is not PEM-decodable certificate / private-key material,
 * or parts of the pair are missing.
 */
"parse" | 
/**
 * The leaf's validity window ended before `now`.
 */
"expired" | 
/**
 * The leaf's validity window starts after `now`.
 */
"notYetValid" | 
/**
 * The configured domain is not covered by the leaf's SANs.
 */
"domainMismatch" | 
/**
 * The chain cannot reach a trust anchor because an intermediate is
 * missing from the imported material.
 */
"incompleteChain" | 
/**
 * The chain resolves structurally but its root is not a publicly
 * trusted CA (self-signed or private CA — phones will not trust it).
 */
"notPubliclyTrusted" | 
/**
 * The private key does not match the leaf certificate's public key.
 */
"keyMismatch" | 
/**
 * Writing the protected storage failed.
 */
"storage"
/**
 * One command answer: the stored/imported summary on success, the
 * readable problems when validation refused the material.
 */
export type HttpsValidationOutcome = { summary: HttpsCertificateSummary | null; problems: HttpsProblem[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Manifest = { schemaVersion: number; id: string; name: string; version: string; description: string | null; scoreServer: ScoreServer; audio: AudioConfig; 
/**
 * v1.4.0 (issue #58): the work declares cross-internet (telematic)
 * performance capability. Gates the App's hub-variable injection and
 * the「设置节点」start gate — carries no hub configuration itself.
 * Lenient by contract (manifest.md): only an explicit `true` declares;
 * absent, `null`, `false` and non-boolean values all read as
 * undeclared and never fail validation.
 */
telematic?: boolean | null; 
/**
 * v1.4.0 (issue #62): the performer connection address (a host string
 * like `mywork.local`) that replaces the LAN IPv4 injected as
 * `PNDS_HOST_IP`. The QR code and the monitor then show this address
 * instead of the numeric IP; absent falls back to the LAN selection
 * (today's behavior). Declaration-only — the Project keeps reading
 * the same variable, zero project changes.
 */
performerAddress?: string | null }
/**
 * A queued `.pnds` bundle finished installing (formerly
 * `pnds:open-bundle`) — the frontend opens the installed project.
 */
export type OpenBundleEvent = Record<string, never>
export type PackResult = { outputPath: string; sha256: string }
/**
 * Who is listening on a project port.
 */
export type PortOccupant = { pid: number; 
/**
 * Short process name — the first token of the full command line.
 */
name: string; 
/**
 * Full command line, for the confirm dialog and the error page.
 */
commandLine: string }
/**
 * Occupancy of one TCP port.
 */
export type PortStatus = { port: number; occupant: PortOccupant | null }
/**
 * A named one-level group of project paths (spec issue #4).
 */
export type ProjectFolder = { id: string; name: string; projectPaths: string[]; 
/**
 * v1.5.0 (#124): the folder's self-written intro (文件夹自述) — plain
 * text the in-app form edits; the setlist export later synthesizes it
 * into the exported README.md. `None` = never written (empty state);
 * pre-v1.5.0 preference files serde-default here, so old data loads
 * as the empty state with no migration step. App-local, never touches
 * project manifests; rides the project-index persistence.
 */
intro?: string | null }
/**
 * v1.5.0 (#130): the projection window came or went — observed at the
 * run-event level (every close path: the ⌘W dispatch, the red traffic
 * light, app quit), so the main window can render the ▶ gate button
 * only while a venue screen actually exists.
 */
export type ProjectionWindowEvent = { exists: boolean }
export type ScoreServer = { entry: string; workingDirectory: string; performerPort: number; monitorPort: number; 
/**
 * #138: the work reads the Host-provided full performer URL
 * (`PNDS_PERFORMER_URL`) — QR, copied address and browser config
 * from that one URL, page scripts and Socket.IO same-origin under
 * the external HTTPS entry, monitor on its internal connection.
 * Declaration-only (no gateway exists yet): it tells a future
 * HTTPS entry that this work adapts, so undeclared works can be
 * offered the explicit HTTP fallback instead of a silent
 * downgrade. Lenient by contract (manifest.md): absent, `null`,
 * `false` and non-boolean values all read as undeclared and never
 * fail validation.
 */
supportsPerformerUrl?: boolean | null; 
/**
 * User request after #174: does this work need the HTTPS entry to
 * perform? Opt-in — only an explicit `true` declares the need;
 * absent, `null`, `false` and non-boolean values all mean the work
 * performs without the entry (every legacy project), so the「not
 * adapted」notice and the HTTP-fallback question never appear for
 * it. With `true`, an undeclared `supports_performer_url` work
 * gets the explicit fallback choice instead of a silent downgrade.
 */
needsHttps?: boolean | null }
export type ScsynthConfig = { 
/**
 * Issue #20: legacy field, read and ignored. The App's global
 * sample-rate preference is the sole boot authority; manifests no
 * longer declare `sampleRate` and validation never requires it. Kept
 * on the struct (with a placeholder default) so manifests that still
 * carry it — existing works, bundled .pnds — load losslessly.
 */
sampleRate?: number; blockSize: number; audioBusChannels: number }
/**
 * Session snapshot emitted to the frontend as the `pnds:session` event.
 */
export type SessionSnapshot = { status: SessionStatus; projectName: string | null; projectPath: string | null; audioMode: AudioMode | null; lanIp: string | null; 
/**
 * #62: the connection address actually injected as `PNDS_HOST_IP` —
 * the manifest-declared performer address when present, else the
 * selected LAN IP. The monitor origin and every shareable address
 * derive from it; `lan_ip` stays the operator's selection fact.
 */
hostAddress: string | null; oscTarget: string | null; health: HealthPayload | null; error: string | null; outputTail: string[]; 
/**
 * Master volume percent (§7.5; new N<=2 sessions always start at 80,
 * N>2 sessions are fixed at 100).
 */
volume: number; 
/**
 * Five-stage loading animation dot (1–5); app-behavior「Loading」.
 */
startupStage: number; 
/**
 * §7.1: internal channel plan (N/H/K/B), present for internal sessions.
 */
channelPlan: ChannelPlan | null; 
/**
 * Final CoreAudio output device in use (internal sessions).
 */
outputDevice: string | null; 
/**
 * #130: the projection start gate (投影开演) — true once the conductor
 * has revealed the monitor on the venue screen, false while it holds
 * the 简介 (project README) screen. Session-level and
 * Rust-authoritative: `reset_run_state` returns it to false on every
 * Load/switch, and both windows plus the ⌘⏎ menu accelerator act
 * through `SessionManager::toggle_projection_start` so neither can
 * drift. Survives the projection window closing (the gate is a
 * session fact, not a window fact).
 */
projectionStarted: boolean; 
/**
 * #140: the trusted-HTTPS entry's own state — independent from the
 * session status because a healthy local server and a usable entry
 * are two facts (§15). `off` for every pre-#140-shaped start
 * (switch off, project undeclared, no session).
 */
httpsEntry: HttpsEntryState; 
/**
 * #174: the performance DNS mapping's own state — a mapping the
 * background daemon holds for THIS session, installed after the
 * entry gateway binds and verified in-daemon before it counts.
 * Independent from `https_entry` (DNS reachable ≠ HTTPS serving);
 * `off` whenever no mapping was requested or the daemon is absent.
 */
dnsMapping: DnsMappingState }
/**
 * Session state publication — every snapshot the state machine emits
 * (formerly `pnds:session`); statuses per runtime-contract §8/§9.
 */
export type SessionSnapshotEvent = { snapshot: SessionSnapshot }
/**
 * The session state machine's vocabulary (runtime-contract §8/§9).
 * Previously a bare `String` on `SessionInner`/`SessionSnapshot`, so a
 * typo compiled and only surfaced mid-performance. serde pins the wire
 * format (`idle | starting | ready | error | stopping`) — the frontend
 * snapshot type and runtime-contract.md see no change, but a missed
 * match arm stops compiling instead of shipping.
 */
export type SessionStatus = "idle" | "starting" | "ready" | "error" | "stopping"
/**
 * v1.4.0 (#63): one `.pnds` found in an export directory, with the
 * identity the import matches entries on.
 */
export type SetlistBundleFile = { path: string; fileName: string; id: string; version: string }
/**
 * Setlist folder export progress (formerly
 * `pnds:setlist-export-progress`), emitted once per packed project.
 */
export type SetlistExportProgressEvent = { done: number; total: number; fileName: string }
/**
 * v1.4.0 (#59): the finished export's location (Finder reveal target).
 */
export type SetlistExportResult = { outputDir: string }
/**
 * v1.4.0 (#59): what the frontend needs to assemble one set.json entry —
 * the manifest identity plus the `.pnds` file name the export will
 * produce. `path` rides along so the caller pairs infos with its request
 * order explicitly.
 */
export type SetlistProjectInfo = { path: string; id: string; version: string; 
/**
 * The manifest's declared default audio mode.
 */
defaultAudioMode: AudioMode; 
/**
 * The `<sanitized name>-<version>.pnds` artifact this export writes.
 */
fileName: string }
/**
 * v1.4.0 (#63): what the import reads out of an export directory — the
 * raw set.json body (the frontend's `parseSetlist` is the validation
 * seam; this side only proves the file exists and reads), the README.md
 * body (#126: the folder 自述 the import parses the intro back from),
 * plus every `.pnds` beside it with its probed identity.
 */
export type SetlistReadout = { setlistJson: string; bundles: SetlistBundleFile[]; 
/**
 * #126: `None` when the directory holds no README.md (pre-v1.5.0
 * exports carry README.txt only) or it is unreadable — the intro
 * then lands on its empty state. Lenient by design: this is
 * matching data, not validation, and an error here would reroute
 * the open flow away from a valid set.
 */
readme: string | null }
export type SynthdefCompileResult = { 
/**
 * The sclang binary this run used (standard app path or PATH hit).
 */
sclangPath: string; 
/**
 * Basenames of the `.scsyndef` artifacts written during this run
 * (modified within the run window), sorted.
 */
produced: string[]; 
/**
 * The `manifest.audio.synthdefs` references confirmed on disk after
 * the compile (empty for projects that do not support internal mode).
 */
verified: string[] }
/**
 * The window regained macOS focus (formerly `pnds:window-focus`).
 * Payload-less by design: every consumer re-derives from the stores
 * (AppShell restores the session snapshot, MonitorView reclaims the
 * keyboard focus). lib.rs re-fires it on a delay schedule because an
 * emit into a still-suspended webview is dropped outright.
 */
export type WindowFocusEvent = Record<string, never>
/**
 * Window chrome state publication (formerly `pnds:window`).
 */
export type WindowStateEvent = { snapshot: WindowStateSnapshot }
/**
 * Window state broadcast to the frontend (WindowStateEvent).
 */
export type WindowStateSnapshot = { 
/**
 * Native macOS fullscreen state.
 */
fullscreen: boolean; 
/**
 * Whether the sidebar's custom traffic lights should be visible.
 * False while the native (unified) title bar is showing.
 */
showCustomTrafficLights: boolean; 
/**
 * Monotonic counter — bumped on every fullscreen/fade transition so
 * the frontend can re-sync. Independent of the monitor reload nonce:
 * fullscreen changes never reload the monitor.
 */
generation: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
