// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * §7.4: the one and only fullscreen toggle. All three entry points
 * (menu, ⌃⌘F, sidebar button) funnel through this command.
 */
async toggleFullscreen() : Promise<Result<WindowStateSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_fullscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §7.4 fade-out then hide (red light / Close Window). Interruptible:
 * a newer request cancels the ramp and the terminal action still runs
 * from a deterministic state.
 */
async closeWindowWithFade() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window_with_fade") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §7.4: first show / dock reopen — fade in from transparent.
 */
async fadeInWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fade_in_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Queries the current window snapshot (initial state on frontend mount).
 */
async getWindowState() : Promise<Result<WindowStateSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Marks the app as quitting so in-flight fades cancel and future fade
 * commands hide immediately (⌘Q must not wait for an animation).
 */
async markQuitting() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_quitting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full preflight for a candidate project directory (§8.1 step 1):
 * orphan cleanup → manifest validation → dependency check → port check.
 * Returns the validated manifest so the frontend can show project info.
 */
async preflightProject(path: string) : Promise<Result<Manifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preflight_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cleans up child processes left behind by an abnormal previous exit.
 * Also runs automatically at app startup and at the start of preflight.
 */
async cleanupOrphanedProcesses() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_orphaned_processes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts the score server of a validated project (§8.1). Progress and
 * health updates are delivered via `pnds:session` events. `osc_target` is
 * required (and validated) only for external mode (§6.6).
 */
async startProject(path: string, mode: string, lanIp: string, oscTarget: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_project", { path, mode, lanIp, oscTarget }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops the running score server (§8.2). Idempotent.
 */
async stopProject() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current session snapshot (frontend restores state on load).
 */
async getSessionState() : Promise<Result<SessionSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §6.4: set the master volume (0-100, dB-linear; live via OSC in internal
 * mode). External/none modes store the value but apply nothing.
 */
async setMasterVolume(percent: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_master_volume", { percent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Usable LAN IPv4 addresses (§7). The user must choose when more than
 * one exists; loopback is never offered.
 */
async listLanAddresses() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_lan_addresses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * §7.6: CoreAudio output devices with their usable output channel count
 * at the given project sample rate, plus the system default. Always
 * re-enumerates (the settings UI must see hot-plugged devices), while
 * session start reuses the process cache.
 */
async listOutputDevices(sampleRate: number) : Promise<Result<AudioDeviceCapabilities, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_output_devices", { sampleRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * User's preferred language (V1 ships English-only)
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * §6.5: chosen CoreAudio output device name. `None` = system default.
 * This is an app-local preference and never touches project manifests.
 */
outputDevice?: string | null; 
/**
 * §6.6: last valid external OSC target per project id.
 */
oscTargets?: Partial<{ [key in string]: string }>; 
/**
 * §4.1: recently-opened (and trusted) project paths. Appended on first
 * trust, kept across launches. Removing from the sidebar drops it here.
 */
recentProjects?: string[] }
export type AudioConfig = { defaultMode: string; supportedModes: string[]; 
/**
 * Discrete project output signals (spec §3.3): 1..=64, default 2.
 * Not a speaker layout — the App never downmixes.
 */
outputChannels?: number; synthdefs: string[] | null; scsynth: ScsynthConfig | null; 
/**
 * Debug-only fallback for standalone runs. The App must never use it;
 * internal mode OSC targets are always dynamically assigned (§5.2).
 */
standaloneTarget: string | null }
/**
 * §7.6: sample-rate-aware device capabilities (name = scsynth -H value).
 */
export type AudioDeviceCapabilities = { devices: AudioOutputDevice[]; sampleRate: number }
/**
 * §7.6: one CoreAudio output device and what it can do at the project's
 * sample rate. `maxOutputChannels` is 0 when no configuration of the
 * device supports that rate.
 */
export type AudioOutputDevice = { name: string; isDefault: boolean; maxOutputChannels: number }
/**
 * §7.1: the Internal channel plan computed at session start.
 */
export type ChannelPlan = { 
/**
 * N: discrete signals the project produces (manifest audio.outputChannels).
 */
projectChannels: number; 
/**
 * H: channels the output device offers at the project sample rate.
 */
deviceChannels: number; 
/**
 * K: channels actually bridged to hardware, min(N, H).
 */
bridgedChannels: number; 
/**
 * B: first private project bus; equals K.
 */
privateBusStart: number }
export type HealthAudio = { 
/**
 * `starting | ready | error | disabled` (disabled = none mode, §9.1)
 */
status: string; target?: string | null; error?: string | null }
/**
 * §9.1 health payload. Only the contract fields are modeled; the App must
 * not rely on anything else.
 */
export type HealthPayload = { 
/**
 * `starting | ready | error | stopping`
 */
status: string; projectId?: string | null; audioMode?: string | null; audio?: HealthAudio | null; scoreServer?: HealthScoreServer | null }
export type HealthScoreServer = { performerPort?: number | null; monitorPort?: number | null; error?: string | null }
export type Manifest = { schemaVersion: number; id: string; name: string; version: string; description: string | null; scoreServer: ScoreServer; audio: AudioConfig }
export type ScoreServer = { entry: string; workingDirectory: string; performerPort: number; monitorPort: number }
export type ScsynthConfig = { sampleRate: number; blockSize: number; audioBusChannels: number }
/**
 * Session snapshot emitted to the frontend as the `pnds:session` event.
 */
export type SessionSnapshot = { 
/**
 * `idle | starting | ready | error | stopping`
 */
status: string; projectName: string | null; projectPath: string | null; audioMode: string | null; lanIp: string | null; oscTarget: string | null; health: HealthPayload | null; error: string | null; outputTail: string[]; 
/**
 * Master volume percent (§7.5; new N<=2 sessions always start at 80,
 * N>2 sessions are fixed at 100).
 */
volume: number; 
/**
 * §10.3 five-stage loading animation dot (1–5).
 */
startupStage: number; 
/**
 * §7.1: internal channel plan (N/H/K/B), present for internal sessions.
 */
channelPlan: ChannelPlan | null; 
/**
 * Final CoreAudio output device in use (internal sessions).
 */
outputDevice: string | null }
/**
 * Window state broadcast to the frontend (`pnds:window` event).
 */
export type WindowStateSnapshot = { 
/**
 * Native macOS fullscreen state.
 */
fullscreen: boolean; 
/**
 * Whether the sidebar's custom traffic lights should be visible.
 * False while the native (unified) title bar is showing.
 */
showCustomTrafficLights: boolean; 
/**
 * Monotonic counter — bumped on every fullscreen/fade transition so
 * the frontend can re-sync. Independent of the monitor reload nonce:
 * fullscreen changes never reload the monitor (§7.2).
 */
generation: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
