use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{bundle, notifications, preferences, project, synthdef, system, tools};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        crate::window::toggle_fullscreen,
        crate::window::close_window_with_fade,
        crate::window::fade_in_window,
        crate::window::get_window_state,
        crate::window::mark_quitting,
        crate::window::quit_app,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        project::preflight_project,
        project::cleanup_orphaned_processes,
        project::start_project,
        project::stop_project,
        project::get_session_state,
        project::set_master_volume,
        project::list_lan_addresses,
        project::list_output_devices,
        project::list_supported_sample_rates,
        project::check_port_status,
        project::release_port,
        bundle::get_bundle_output_info,
        bundle::pack_project_bundle,
        bundle::install_bundle,
        bundle::reclaim_project_bundle,
        bundle::take_pending_bundle_opens,
        bundle::pick_project_or_bundle,
        synthdef::compile_project_synthdefs,
        tools::builtin_utilities,
        system::open_app_data_dir,
        system::open_app_log_dir,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
